TRUNCATE Customers;
TRUNCATE Passwords;
TRUNCATE OverdraftLogs;
TRUNCATE TransactionHistory;
TRUNCATE TransferHistory;
TRUNCATE CryptoHistory;
TRUNCATE CryptoHoldings;
TRUNCATE TerrapinExpressHistory;
TRUNCATE TerrapinExpressHoldings;